version: "3"

services:
  prognoz:
    image: prognoz:latest
    restart: 'always'
    volumes:
      - ./data/html:/var/www/html
    
      
  nginx:
    image: nginx
    restart: 'always'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
        - "${NGINX_PORT}:80"
    links:
      - prognoz
